services:
  - type: web
    name: choir-api
    runtime: docker
    dockerfilePath: api/Dockerfile
    dockerContext: .
    envVars:
      - key: SUI_PRIVATE_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AZURE_API_BASE
        sync: false
      - key: AZURE_API_VERSION
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /health
